#pragma once
#ifndef __guiMyFrame__
#define __guiMyFrame__

/**
@file
Subclass of MyFrame, which is generated by wxFormBuilder.
*/

#include "gui.h"
#include <map>
#include "wx/dataview.h"
#include "../models.h"
#include "../treeModel.h"
#include "../MyGridTable.h"
#include "../ImageRenderer.h"

//// end generated include

/** Implementing MyFrame */
class guiMainFrame : public MainFrame
{
	public:
		guiMainFrame( wxWindow* parent );
		void OnQuit(wxCommandEvent& event);
		void OnAbout(wxCommandEvent& event);
		void OnNameSort(wxCommandEvent& event);
		void OnImageFilter(wxCommandEvent& event);
		void build_tree();
		void UpdateGrid();

		wxMenu* menu_file_close;
		wxMenu* menu_help_about;
		wxTreeItemId tree_add(const wxTreeItemId& parent, const wxString& text, int tree_node);
		std::map<int, wxTreeItemId> tree_data;

		wxObjectDataPtr<MusicModel> m_music_model;
		wxObjectDataPtr<TreeModel> treeModel;
		wxDataViewColumn* m_col;
		wxDataViewCtrl* m_ctrl;
		MyGridTable* gridTable;

		bool isNameSorted = true;
		bool isFilterImage = false;
};

class LayoutGridItem
{
public:
	std::string name;
	wxBitmap icon;
	bool checkbox;
};

#endif // __guiMyFrame__
